#spring.application.name=shop_51


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/g_51_shop
    username: my_user
    password: pos1234
    driver-class-name: org.postgresql.Driver

  application:
    name: Shop

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  mail:
    username: lorageo33@gmail.com
    password: wqwyvmampubepbvq
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com


server:
  servlet:
    context-path: /api

logging:
  file:
    name: logs/log.log
  level:
    root: info

messages:
  hello: Hello from local application!






